apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: watson-criu-nolimits-sample
  labels:
    app: watson-criu-nolimits-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: watson-criu-nolimits-deployment
        app: watson-criu-nolimits-deployment
        version: v1
      annotations:
        container.seccomp.security.alpha.kubernetes.io/watson-criu-nolimits-springapp: unconfined
        container.apparmor.security.beta.kubernetes.io/watson-criu-nolimits-springapp: unconfined
    spec:
      containers:
      - name: watson-criu-nolimits-springapp
        image: dinogun/watson-springboot:openj9-v8.criu-checkpoint
        imagePullPolicy: Always
        securityContext:
          capabilities:
            add:
              - AUDIT_CONTROL
              - DAC_READ_SEARCH
              - NET_ADMIN
              - SYS_ADMIN
              - SYS_PTRACE
              - SYS_RESOURCE
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: watson-criu-nolimits-service
  labels:
    app: watson-criu-nolimits-app
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32226
      targetPort: 8080
      name: http
  selector:
    name: watson-criu-nolimits-deployment
