apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: watsonex-criu
  labels:
    app: watsonex-criu-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: watsonex-criu-deployment
        app: watsonex-criu-deployment
        version: v1
    spec:
      serviceAccountName: watsonex-criu-sa
      containers:
      - name: watsonex-criu-springapp
        image: dinogun/watsonex-springboot:openj9-v8.criu-checkpoint
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: watsonex-criu-service
  labels:
    app: watsonex-criu-app
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 32226
      targetPort: 8080
      name: http
  selector:
    name: watsonex-criu-deployment
